# Generated by Django 4.1.5 on 2023-08-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookshop',
            options={},
        ),
    ]
