# Generated by Django 4.1.5 on 2023-08-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bookshop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookshop',
            options={'permissions': [('can_access_bookshop_api', 'Can access Bookshop API')]},
        ),
    ]
