# Generated by Django 4.1.5 on 2023-08-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bookshop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookshop',
            options={'permissions': [('can_change_bookshop', 'Can change Bookshop')]},
        ),
    ]
