# Generated by Django 4.1.5 on 2023-08-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_bookshop_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaraunts',
            new_name='Restaurants',
        ),
        migrations.AlterModelOptions(
            name='bookshop',
            options={'permissions': [('can_change_bookshop', 'can change bookshop')]},
        ),
        migrations.AlterModelOptions(
            name='clinics',
            options={'permissions': [('can_change_clinics', 'can change clinics')]},
        ),
        migrations.AlterModelOptions(
            name='petshop',
            options={'permissions': [('can_change_petshop', 'can change petshop')]},
        ),
        migrations.AlterModelOptions(
            name='restaurants',
            options={'permissions': [('can_change_restaurants', 'can change restaurants')]},
        ),
    ]
